/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.crs.view;

import java.sql.ResultSet;
import java.sql.Connection;
import edu.ijse.crs.db.DBconnection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author HP
 */
public class StudentForm extends javax.swing.JFrame {
    
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs = null;

    /**
     * Creates new form StudentForm
     */
    public StudentForm() throws ClassNotFoundException, SQLException {
        initComponents();
        conn = DBconnection.getInstance().getConnection();
        tableload();
    }
     public void tableload(){
         try {
        String sql = "SELECT StudentID, StudentName, DOB, Program, Year, Phone FROM student";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();

        DefaultTableModel model = new DefaultTableModel();

        // Add columns
        java.sql.ResultSetMetaData rsmd = rs.getMetaData();
        int columnCount = rsmd.getColumnCount();
        for (int i = 1; i <= columnCount; i++) {
            model.addColumn(rsmd.getColumnName(i));
        }

        // Add rows
        while (rs.next()) {
            Object[] row = new Object[columnCount];
            for (int i = 0; i < columnCount; i++) {
                row[i] = rs.getObject(i + 1);
            }
            model.addRow(row);
        }

        studentDetailTable.setModel(model);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    } finally {
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
       }
   
     }
     public void tabledata(){
         int raw=studentDetailTable.getSelectedRow();
         String sid = studentDetailTable.getValueAt(raw, 0).toString();
         String sName = studentDetailTable.getValueAt(raw, 1).toString();
         String DOB = studentDetailTable.getValueAt(raw, 2).toString();
         String program = studentDetailTable.getValueAt(raw, 3).toString();
         String year = studentDetailTable.getValueAt(raw, 4).toString();
         String scontact = studentDetailTable.getValueAt(raw, 5).toString();
         
         studentIDtxt.setText(sid);
         studentNametxt.setText(sName);
         studentDOBtxt.setText(DOB);
         studentProgramtxt.setText(program);
         studentYeartxt.setText(year);
         studentContacttxt.setText(scontact);
         
         
     }
     public void searchbox(){
         String searchb=searchByIDtxt.getText();
         
         try {
             String sql="SELECT * FROM student WHERE StudentID LIKE '%"+searchb+"%' OR StudentName LIKE '%"+searchb+"%'";
             pst=conn.prepareCall(sql);
             rs=pst.executeQuery();
             studentDetailTable.setModel(DbUtils.resultSetToTableModel(rs));
             
         } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e);
         }
     }
     
     public void updatebtn(){
         
     
     
     }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        studentIDlbl = new javax.swing.JLabel();
        studentIDtxt = new javax.swing.JTextField();
        studentNamelbl = new javax.swing.JLabel();
        studentNametxt = new javax.swing.JTextField();
        studentDOBlbl = new javax.swing.JLabel();
        studentDOBtxt = new javax.swing.JTextField();
        studentProgramlbl = new javax.swing.JLabel();
        studentProgramtxt = new javax.swing.JTextField();
        studentYearlbl = new javax.swing.JLabel();
        studentYeartxt = new javax.swing.JTextField();
        studentContectlbl = new javax.swing.JLabel();
        studentContacttxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentDetailTable = new javax.swing.JTable();
        searchByID = new javax.swing.JPanel();
        searchByIDtxt = new javax.swing.JTextField();
        updateStudentbtn = new javax.swing.JButton();
        addStudentbtn1 = new javax.swing.JButton();
        deleteStudentbtn = new javax.swing.JButton();
        acdemicRecordbtn = new javax.swing.JButton();
        courseBtn = new javax.swing.JButton();
        entrolmentbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("STUDENT FORM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(446, 446, 446)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        studentIDlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        studentIDlbl.setText("Student ID");

        studentNamelbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        studentNamelbl.setText("Student Name");

        studentDOBlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        studentDOBlbl.setText("DOB");

        studentProgramlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        studentProgramlbl.setText("Program");

        studentYearlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        studentYearlbl.setText("Year");

        studentContectlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        studentContectlbl.setText("Contact");

        studentDetailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        studentDetailTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentDetailTableMouseClicked(evt);
            }
        });
        studentDetailTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                studentDetailTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(studentDetailTable);

        searchByID.setBackground(new java.awt.Color(153, 255, 204));
        searchByID.setBorder(javax.swing.BorderFactory.createTitledBorder("Search by ID or Name"));

        searchByIDtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchByIDtxtKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout searchByIDLayout = new javax.swing.GroupLayout(searchByID);
        searchByID.setLayout(searchByIDLayout);
        searchByIDLayout.setHorizontalGroup(
            searchByIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchByIDtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
        );
        searchByIDLayout.setVerticalGroup(
            searchByIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchByIDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchByIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        updateStudentbtn.setBackground(new java.awt.Color(153, 255, 255));
        updateStudentbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updateStudentbtn.setText("UPDATE");
        updateStudentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStudentbtnActionPerformed(evt);
            }
        });

        addStudentbtn1.setBackground(new java.awt.Color(204, 255, 204));
        addStudentbtn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addStudentbtn1.setText("ADD");
        addStudentbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentbtn1ActionPerformed(evt);
            }
        });

        deleteStudentbtn.setBackground(new java.awt.Color(255, 153, 153));
        deleteStudentbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deleteStudentbtn.setText("DELETE");
        deleteStudentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentbtnActionPerformed(evt);
            }
        });

        acdemicRecordbtn.setBackground(new java.awt.Color(255, 153, 255));
        acdemicRecordbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        acdemicRecordbtn.setText("ACADEMIC RECORD");
        acdemicRecordbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acdemicRecordbtnActionPerformed(evt);
            }
        });

        courseBtn.setBackground(new java.awt.Color(255, 153, 255));
        courseBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        courseBtn.setText("COUSRE");
        courseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseBtnActionPerformed(evt);
            }
        });

        entrolmentbtn.setBackground(new java.awt.Color(255, 153, 255));
        entrolmentbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        entrolmentbtn.setText("ENROLMENT");
        entrolmentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrolmentbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(searchByID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(addStudentbtn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateStudentbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteStudentbtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(studentYearlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(studentYeartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(studentProgramlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(studentProgramtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(studentDOBlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(studentDOBtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(studentNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(studentNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(studentIDlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(studentIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(studentContectlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(studentContacttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                        .addComponent(acdemicRecordbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(courseBtn)
                        .addGap(18, 18, 18)
                        .addComponent(entrolmentbtn)
                        .addGap(69, 69, 69))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentIDlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentDOBlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentDOBtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentProgramlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentProgramtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentYearlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentYeartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentContectlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentContacttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(searchByID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addStudentbtn1)
                            .addComponent(updateStudentbtn)
                            .addComponent(deleteStudentbtn))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(acdemicRecordbtn)
                            .addComponent(courseBtn)
                            .addComponent(entrolmentbtn))
                        .addGap(121, 121, 121))))
        );

        searchByID.getAccessibleContext().setAccessibleName("Search by ID or Name");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateStudentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStudentbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateStudentbtnActionPerformed

    private void addStudentbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentbtn1ActionPerformed
        // TODO add your handling code here:
        String sID;
        String sName;
        String sDOB;
        String program;
        int year;
        String scontact;
        
        sID=studentIDtxt.getText();
        sName=studentNametxt.getText();
        sDOB=studentDOBtxt.getText();
        program=studentProgramtxt.getText();
        year=Integer.parseInt(studentYeartxt.getText());
        scontact=studentContacttxt.getText();
        
        try {
            String sql="INSERT INTO student( StudentID, StudentName,DOB,Program,Year,Phone)VALUES ('"+sID+"','"+sName+"','"+sDOB+"','"+program+"','"+year+"','"+scontact+"')";
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data added sucessfuly...");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        
        tableload();
       
        
        
    }//GEN-LAST:event_addStudentbtn1ActionPerformed

    private void deleteStudentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteStudentbtnActionPerformed

    private void acdemicRecordbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acdemicRecordbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acdemicRecordbtnActionPerformed

    private void courseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseBtnActionPerformed

    private void entrolmentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrolmentbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrolmentbtnActionPerformed

    private void studentDetailTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentDetailTableMouseClicked
        // TODO add your handling code here:
        tabledata();
    }//GEN-LAST:event_studentDetailTableMouseClicked

    private void studentDetailTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentDetailTableKeyReleased
        // TODO add your handling code here:
        tabledata();
    }//GEN-LAST:event_studentDetailTableKeyReleased

    private void searchByIDtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchByIDtxtKeyReleased
        // TODO add your handling code here:
        searchbox();
    }//GEN-LAST:event_searchByIDtxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new StudentForm().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(StudentForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(StudentForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acdemicRecordbtn;
    private javax.swing.JButton addStudentbtn1;
    private javax.swing.JButton courseBtn;
    private javax.swing.JButton deleteStudentbtn;
    private javax.swing.JButton entrolmentbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel searchByID;
    private javax.swing.JTextField searchByIDtxt;
    private javax.swing.JTextField studentContacttxt;
    private javax.swing.JLabel studentContectlbl;
    private javax.swing.JLabel studentDOBlbl;
    private javax.swing.JTextField studentDOBtxt;
    private javax.swing.JTable studentDetailTable;
    private javax.swing.JLabel studentIDlbl;
    private javax.swing.JTextField studentIDtxt;
    private javax.swing.JLabel studentNamelbl;
    private javax.swing.JTextField studentNametxt;
    private javax.swing.JLabel studentProgramlbl;
    private javax.swing.JTextField studentProgramtxt;
    private javax.swing.JLabel studentYearlbl;
    private javax.swing.JTextField studentYeartxt;
    private javax.swing.JButton updateStudentbtn;
    // End of variables declaration//GEN-END:variables
}
