/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.crs.view;

import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class studentLogin extends javax.swing.JFrame {

    /**
     * Creates new form studentLogin
     */
    public studentLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        studentIDlbl = new javax.swing.JLabel();
        studentpasswordlbl = new javax.swing.JLabel();
        studentregisterbtn = new javax.swing.JButton();
        studentloginbtn1 = new javax.swing.JButton();
        studentIDtxt = new javax.swing.JTextField();
        studentpasswordtxt = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Student Login ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 170, 50));

        studentIDlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        studentIDlbl.setText("User ID");
        jPanel1.add(studentIDlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 100, 40));

        studentpasswordlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        studentpasswordlbl.setText("Password");
        jPanel1.add(studentpasswordlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 100, 40));

        studentregisterbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        studentregisterbtn.setText("Register");
        studentregisterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentregisterbtnActionPerformed(evt);
            }
        });
        jPanel1.add(studentregisterbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 100, 40));

        studentloginbtn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        studentloginbtn1.setText("Login");
        studentloginbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentloginbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(studentloginbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 100, 40));
        jPanel1.add(studentIDtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 132, 340, 40));
        studentIDtxt.getAccessibleContext().setAccessibleParent(studentIDlbl);

        jPanel1.add(studentpasswordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 310, 40));
        studentpasswordtxt.getAccessibleContext().setAccessibleParent(studentpasswordtxt);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentregisterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentregisterbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentregisterbtnActionPerformed

    private void studentloginbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentloginbtn1ActionPerformed
        // TODO add your handling code here:
        String studentId;//nuwan
        String spassword;//1234
        
        studentId=studentIDtxt.getText();
        spassword=studentpasswordtxt.getText();
        
        if(studentId.equals("nuwan") && spassword.equals("1234")){
            StudentDetails studentDetailsF = new StudentDetails();
            studentDetailsF.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null,"UserID or Password incorrect please try again..!");
        }

    }//GEN-LAST:event_studentloginbtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel studentIDlbl;
    private javax.swing.JTextField studentIDtxt;
    private javax.swing.JButton studentloginbtn1;
    private javax.swing.JLabel studentpasswordlbl;
    private javax.swing.JPasswordField studentpasswordtxt;
    private javax.swing.JButton studentregisterbtn;
    // End of variables declaration//GEN-END:variables
}
